### ISSUE TITLE
SPaircraft convergence issue

### ISSUE THREAD

**Issue by NoahSchwalb** [convexengineering/SPaircraft#138] opened 2020-02-25 20:30 UTC
The gas constant "R" and graviational acceleration "g" defined in the turbofan repository are both reported to have "no lower bound," thus causing SPaircraft.py to diverge. Error message is attached.
[error.txt](https://github.com/convexengineering/SPaircraft/files/4252034/error.txt)

**Comment by 1ozturkbe** [comment] 2020-02-25 20:32
Just posting full text here:
``` python
C:\Users\Schwa\Documents\GitHub\SPaircraft>python SPaircraft.py                                                         Beginning signomial solve.                                                                                              Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 1.98 seconds.                                                                                              Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 1.72 seconds.                                                                                              Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 1.52 seconds.                                                                                              Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 2.01 seconds.                                                                                              Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 1.08 seconds.                                                                                              Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 1.63 seconds.                                                                                              Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 1.65 seconds.                                                                                              Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 2.1 seconds.                                                                                               Using solver 'mosek_cli'                                                                                                Solving for 1749 variables.                                                                                             Solving took 2.19 seconds.                                                                                              Solving took 9 GP solves and 22.9 seconds.                                                                              Traceback (most recent call last):                                                                                        File "SPaircraft.py", line 97, in <module>                                                                                sol = test()                                                                                                          File "SPaircraft.py", line 89, in test                                                                                    sol = optimize_aircraft(m, substitutions, fixedBPR, pRatOpt, mutategparg)                                             File "SPaircraft.py", line 65, in optimize_aircraft                                                                       sol = m_relax.localsolve(verbosity=2, iteration_limit=200, reltol=0.01, mutategp=mutategparg)#, x0 = x0)              File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\prog_factories.py", line 124, in solvefn                                                                                                          result = progsolve(solver, verbosity, **kwargs)                                                                       File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\sgp.py", line 174, in localsolve                                                                                                                  self.process_result(self.result)                                                                                      File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\set.py", line 254, in process_result                                                                                                              constraint.process_result(result)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\set.py", line 254, in process_result                                                                                                              constraint.process_result(result)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\relax.py", line 161, in process_result                                                                                                            ConstraintSet.process_result(self, result)                                                                            File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\set.py", line 254, in process_result                                                                                                              constraint.process_result(result)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\set.py", line 254, in process_result                                                                                                              constraint.process_result(result)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\bounded.py", line 90, in process_result                                                                                                           ConstraintSet.process_result(self, result)                                                                            File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\set.py", line 254, in process_result                                                                                                              constraint.process_result(result)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\set.py", line 254, in process_result                                                                                                              constraint.process_result(result)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\set.py", line 254, in process_result                                                                                                              constraint.process_result(result)                                                                                     [Previous line repeated 1 more time]                                                                                    File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\constraints\tight.py", line 48, in process_result                                                                                                             self.reltol*100, mag(rel_diff)*100))                                                                                  File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\repr_conventions.py", line 178, in __str__                                                                                                                    return self.str_without()  # pylint: disable=no-member                                                                File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\nomials\core.py", line 19, in str_without                                                                                                                     return self.parse_ast(excluded) + units                                                                               File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\repr_conventions.py", line 107, in parse_ast                                                                                                                  left = parenthesize(strify(values[0], excluded), mult=False)                                                          File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\repr_conventions.py", line 64, in strify                                                                                                                      val = try_str_without(val, excluded)                                                                                  File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\small_scripts.py", line 37, in try_str_without                                                                                                                return item.str_without(excluded)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\nomials\core.py", line 19, in str_without                                                                                                                     return self.parse_ast(excluded) + units                                                                               File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\repr_conventions.py", line 107, in parse_ast                                                                                                                  left = parenthesize(strify(values[0], excluded), mult=False)                                                          File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\repr_conventions.py", line 64, in strify                                                                                                                      val = try_str_without(val, excluded)                                                                                  File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\small_scripts.py", line 37, in try_str_without                                                                                                                return item.str_without(excluded)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\nomials\core.py", line 19, in str_without                                                                                                                     return self.parse_ast(excluded) + units                                                                               File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\repr_conventions.py", line 108, in parse_ast                                                                                                                  right = parenthesize(strify(values[1], excluded), mult=False)                                                         File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\repr_conventions.py", line 64, in strify                                                                                                                      val = try_str_without(val, excluded)                                                                                  File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\small_scripts.py", line 37, in try_str_without                                                                                                                return item.str_without(excluded)                                                                                     File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\nomials\core.py", line 19, in str_without                                                                                                                     return self.parse_ast(excluded) + units                                                                               File "C:\Users\Schwa\AppData\Local\Programs\Python\Python37\lib\site-packages\gpkit\repr_conventions.py", line 131, in parse_ast                                                                                                                  aststr = "%s%s" % (left, unichr(176+x))                                                                             TypeError: integer argument expected, got float  
```

**Comment by 1ozturkbe** [comment] 2020-02-25 20:34
I recognize the error. This is something that happens mid-GP solve, which is curious. Pretty certain the cause is that the model no longer closes and it is infeasible. I am just pushing a fix at #139 so we can see if that resolves the issue.

**Comment by 1ozturkbe** [comment] 2020-02-27 22:04
It seems that there is more interest in SPaircraft recently, so I made updates to both turbofan and SPaircraft. Master version of SPaircraft with these updates should close, to a 'satisfactory' optimum. Note that we size things differently relative to TASOPT, so there will be some big diffs. 
Let me know if this doesn't work for you!

**Comment by 1ozturkbe** [comment] 2020-03-07 21:08
Tests are passing on all machines as well as my machine, so closing. Can figure this on a particular machine basis.

**Closed by 1ozturkbe** 2020-03-07 21:08 UTC
