### ISSUE TITLE
Collapsing fan diameter (!?)

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/SPaircraft#125] opened 2018-04-26 19:07 UTC
Although there were no changes to any of the models, the latest push on master has a tiny fan diameter (10^-7m). Will look into shortly.

**Comment by mayork** [comment] 2018-04-26 19:10
do you mean that PR you merged? If so, I think we need to revert until the paper is through reviews unless the cause of the bug is obvious

**Closed** 2018-04-26 19:25 UTC

**Comment by mayork** [comment] 2018-04-26 20:04
Sounds great
